### ISSUE TITLE
Can i use the pdf417-phonegap scanner plugin on an ionic framework project

### ISSUE THREAD

**Issue by shepherdsiduli** [PDF417/pdf417-phonegap#8]

**Comment by jkearse3** [comment]
sheperdsiduli, by any chance could you elaborate on how you got pdf417 working? I'm trying to test it out myself and am having issues trying to get it up and running and can't seem to find where the issue is stemming from as of yet. 

Testing in browser gives me a 'cordova is not defined' which I expect, but when testing in Ionic View, I get no functionality.

I have this [plunker](http://embed.plnkr.co/AE8oGawQgThfGHEtozD0/preview) as an example of how I've used it. Thank so much if anyone responds.

**Comment by ssasa** [comment]
Have you followed steps from this link?

https://github.com/PDF417/pdf417-phonegap

**Comment by jkearse3** [comment]
ssasa, I followed the usage section, although I didn't follow the sample section prior to it. I've been getting the following error when attempting to close the repository:
![screen shot 2015-05-11 at 2 56 17 pm](https://cloud.githubusercontent.com/assets/4030048/7572667/e97535cc-f7ed-11e4-81d3-05fbf39f08d7.png)
Am I missing something?

**Comment by ssasa** [comment]
You can't connect to GitHub ... here are some GitHub troubleshooting
instructions:
https://help.github.com/articles/error-permission-denied-publickey/

**Comment by jkearse3** [comment]
I noticed in the changelog of this repository that the script 'initDemoApp.sh' is the means of building the demo now rather than doing the sample steps listed in the ReadMe. I ran that script and it completed successfully, and after successfully uploading the demo app to ionic view to test, the plugin ended up being unresponsive.

**Comment by lhabjane** [comment]
Hi,

can you please specify more details, how exactly is plugin unresponsive (was plugin initialized or camera was not working ... etc) and can you please provide us with log output during the time when plugin was initialized?

**Comment by jkearse3** [comment]
Hi Ihabjane, apologies for the late response, just now getting time to jump back on this. I actually cannot tell what the error is from ionic view (I'm still looking for a proper way to view logs). I'm sorry I can't be of much more help in terms of errors with testing on my phone (iOS). So I actually cannot tell if the plugin is being initialized or not...

When running in an emulator an alert box saying "This feature is not supported on iOS simulator", which I believe should be correct.

This is the case with both the sample as well as my attempt to use the plugin.

**Comment by lhabjane** [comment]
Hi,

you cannot run the plugin inside the emulator, because emulator has no
camera available, this is as expected.

We don't have experience with ionic view integration, so we cannot give you
a better answer.
Can you please share your minimal demo application with us (zip file,
github repo) to reproduce your problems - this would be a great help for us
to analyze your problem.


LP,
Ljudevit Habjanec

**Comment by jkearse3** [comment]
Here is a demo project I quickly created that houses the issue.
https://github.com/jkearse3/testScanApp

**Comment by bgold0** [comment]
I am having the same issue as @jkearse3 

Was anyone able to successfully get this to work ionic?

**Comment by jkearse3** [comment]
By any chance has there been any update with my particular issue?

**Comment by Cerovec** [comment]
Hi,

unfortunately, we're primarily developing our native iOS and Android SDKs, and didn't get the chance to look into ionic/cordova.

We're reopening this because it's clearly an issue.

Please post some more details about the issue, or use our native SDKs ([iOS](http://github.com/pdf417/pdf417-ios), [Android](https://github.com/pdf417/pdf417-android)).

**Comment by lhabjane** [comment]
Hi, @shepherdsiduli @bgold0 @jkearse3 @Cerovec 
we updated the pdf417 plugin, 
installed the updated plugin, (ionic plugin add command) to your sample project (using the latest ionic framework),
and it works with your sample project on Android platform.  

If you are still having issues during runtime (after succesfully running the app) please start Chrome Remote Debugger and check for issues in JS code.
If it fails during building, well.. we tested on MacOS, so issues on Windows are possible..

**Comment by Cerovec** [comment]
Closing as inactive.
